apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: emissary-ingress
  namespace: emissary
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: emissary-ingress
  mtls:
    mode: STRICT