apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: emissary-ingress
  namespace: emissary
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: emissary-ingress
  ingress:
  - port:
      number: 80
      protocol: HTTP
      name: http
    defaultEndpoint: 127.0.0.1:8080
  - port:
      number: 443
      protocol: HTTPS
      name: https
    defaultEndpoint: 127.0.0.1:8443
  egress:
  - hosts:
    - "*/*"