nameOverride: ""

ollama:
  image:
    # repository: ghcr.io/ggerganov/llama.cpp
    # tag: server-cuda
    repository: ollama/ollama
    tag: "0.5.1"
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: false
  # -- If enabling embedded Ollama, update fullnameOverride to your desired Ollama name value, or else it will use the default ollama.name value from the Ollama chart
  fullnameOverride: "open-webui-ollama"
  # -- Example Ollama configuration with nvidia GPU enabled, automatically downloading a model, and deploying a PVC for model persistence
  ollama:
    resources:
      requests:
        memory: 16384Mi
        cpu: 1000m
      limits:
        memory: 65536Mi
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    # models:
    # - llama3.1
    # - llama3.2
    # - llama3.2-vision
    # - llama3.3
    # - qwq
    # - qwen2.5-coder:32b
    # - snowflake-arctic-embed2
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
    storageClass: "harvester"
    size: 100Gi
  extraEnv:
  - name: OLLAMA_FLASH_ATTENTION
    value: "true"
  - name: OLLAMA_KV_CACHE_TYPE
    value: "q4_0"

pipelines:
  # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
  enabled: true

tika:
  # -- Automatically install Apache Tika to extend Open WebUI
  enabled: true

# -- Open WebUI image tags can be found here: https://github.com/open-webui/open-webui/pkgs/container/open-webui
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "v0.4.8-cuda"
  pullPolicy: "IfNotPresent"
resources:
  requests:
    memory: 4096Mi
    cpu: 500m
persistence:
  enabled: true
  size: 20Gi
  # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
  existingClaim: ""
  # -- If using multiple replicas, you must update accessModes to ReadWriteMany
  accessModes:
    - ReadWriteOnce
  storageClass: "harvester"

# -- OpenAI base API URL to use. Defaults to the Pipelines service endpoint when Pipelines are enabled, and "https://api.openai.com/v1" if Pipelines are not enabled and this value is blank
openaiBaseApiUrl: ""

# -- Additional environments variables on the output Deployment definition. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEY
    value: "0p3n-w3bu!"
  - name: ENABLE_SIGNUP
    value: "false"
  - name: ENABLE_LOGIN_FORM
    value: "false"
  - name: ENABLE_OAUTH_SIGNUP
    value: "true"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "true"
  - name: OPENID_PROVIDER_URL
    value: https://authentik.internal.magiccityit.com/application/o/open-webui/.well-known/openid-configuration
  - name: OAUTH_CLIENT_ID
    value: iS20QUlOMXlFgxBpJU2yX9zPSgeWkxZ3zflmJwLl
  - name: OAUTH_CLIENT_SECRET
    value: kxecToa5L3mDGtgd4LCnRBimFCw9FXUUadz7qEOtImhh79ubl6nJpQH2U76WQjj2EJcNLMB6mXRbj9LOms4DBGfmLBKjrZ391ZXc6tNerNwXmC1IOd3UrxOVns9jBT8k
  - name: OAUTH_SCOPES
    value: openid email profile
  - name: OPENID_REDIRECT_URI
    value: https://open-webui.internal.magiccityit.com/oauth/oidc/callback
  - name: OLLAMA_BASE_URL
    value: http://open-webui-ollama.open-webui.svc.cluster.local:11434
  - name: WEBUI_URL
    value: "https://openwebui.internal.magiccityit.com"
  - name: PDF_EXTRACT_IMAGES
    value: "true"
  - name: RAG_EMBEDDING_MODEL
    value: snowflake-arctic-embed2/latest
  - name: RAG_EMBEDDING_MODEL_AUTO_UPDATE
    value: "true"
  - name: RAG_RERANKING_MODEL
    value: BAAI/bge-reranker-v2-m3
  - name: RAG_RERANKING_MODEL_AUTO_UPDATE
    value: "true"
  - name: CHUNK_SIZE
    value: "3000"
  - name: CHUNK_OVERLAP
    value: "500"
  - name: ENABLE_RAG_WEB_SEARCH
    value: "true"
  - name: ENABLE_SEARCH_QUERY
    value: "true"
  - name: RAG_WEB_SEARCH_ENGINE
    value: "searchxng"
  - name: SEARXNG_QUERY_URL
    value: "https://searxng.internal.magiccityit.com/search?q=<query>"
