nameOverride: ""

ollama:
  image:
    tag: "0.5.1"
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: true
  # -- If enabling embedded Ollama, update fullnameOverride to your desired Ollama name value, or else it will use the default ollama.name value from the Ollama chart
  fullnameOverride: "open-webui-ollama"
  # -- Example Ollama configuration with nvidia GPU enabled, automatically downloading a model, and deploying a PVC for model persistence
  ollama:
    resources:
      requests:
        memory: 16384Mi
        cpu: 1000m
      limits:
        memory: 65536Mi
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    models:
      - llama3.3
      - qwen2.5-coder:32b
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
    storageClass: "microk8s-hostpath"
    size: 100Gi
  extraEnv:
  - name: OLLAMA_FLASH_ATTENTION
    value: "true"

pipelines:
  # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
  enabled: false

tika:
  # -- Automatically install Apache Tika to extend Open WebUI
  enabled: true

# -- Open WebUI image tags can be found here: https://github.com/open-webui/open-webui/pkgs/container/open-webui
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "latest"
  pullPolicy: "IfNotPresent"
resources:
  requests:
    memory: 4096Mi
    cpu: 500m
persistence:
  enabled: true
  size: 20Gi
  # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
  existingClaim: ""
  # -- If using multiple replicas, you must update accessModes to ReadWriteMany
  accessModes:
    - ReadWriteOnce
  storageClass: "microk8s-hostpath"

# -- OpenAI base API URL to use. Defaults to the Pipelines service endpoint when Pipelines are enabled, and "https://api.openai.com/v1" if Pipelines are not enabled and this value is blank
openaiBaseApiUrl: ""

# -- Additional environments variables on the output Deployment definition. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEY
    value: "0p3n-w3bu!"
