# use single binary and filesystem storage for test
# do not use in production
loki:
  useTestSchema: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
minio:
  enabled: false
test:
  enabled: false
lokiCanary:
  enabled: false
monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
    alerting: true
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: true
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
      enableConfigReadAPI: false
  lokiCanary:
    enabled: false
resultsCache:
  enabled: false
chunksCache:
  enabled: false
singleBinary:
  replicas: 1
  storageClass: harvester
deploymentMode: SingleBinary
gateway:
  enabled: false
# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0