apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - vault-k8s
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.25.0
    - repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      path: cert-manager-configuration-guide/services/vault
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
