apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: clearml-serving
  namespace: clearml
spec:
  hosts:
  # - clearml-serving-inference
  # - clearml-serving-inference.clearml
  # - clearml-serving-inference.clearml.svc.cluster.local
  - clearml-serving.internal.magiccityit.com
  gateways:
  # - istio-ingress/internal-magiccityit-gateway
  - emissary/internal-magiccityit-gateway
  - mesh
  http:
  - route:
    - destination:
        host: clearml-serving-inference
        port:
          number: 8080