apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: open-webui-pipelines
spec:
  host: open-webui-pipelines
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1