apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: prometheus
  namespace: emissary
  annotations:
      external-dns.ambassador-service: emissary-ingress.emissary
spec:
  ambassador_id: ["emissary"]
  hostname: "prometheus.internal.magiccityit.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: internal-magiccityit-domain-tls
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: grafana
  namespace: emissary
  annotations:
      external-dns.ambassador-service: emissary-ingress.emissary
spec:
  ambassador_id: ["emissary"]
  hostname: "grafana.internal.magiccityit.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: internal-magiccityit-domain-tls
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: alertmanager
  namespace: emissary
  annotations:
      external-dns.ambassador-service: emissary-ingress.emissary
spec:
  ambassador_id: ["emissary"]
  hostname: "alertmanager.internal.magiccityit.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: internal-magiccityit-domain-tls