apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: prometheus-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: prometheus.internal.magiccityit.com
  prefix: /
  service: prometheus-k8s.monitoring:9090
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grafana-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: grafana.internal.magiccityit.com
  prefix: /
  service: grafana.monitoring:3000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: alertmanager-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: alertmanager.internal.magiccityit.com
  prefix: /
  service: alertmanager-main.monitoring:9093