apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-tracing
  namespace: argocd
spec:
  destination:
    namespace: jaeger-tracing
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jaeger
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 3.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
