apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubed
    repoURL: https://charts.appscode.com/stable/
    targetRevision: v0.13.2
    helm:
      parameters:
      - name: operator.registry
        value: rancher
      - name: operator.repository
        value: mirrored-appscode-kubed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
