apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/jonathanelbailey/homelab.catalog.git'
    path: devqa/services/ollama
    targetRevision: HEAD
  sources:
    - chart: open-webui
      helm:
        valueFiles:
          - >-
            $values/devqa/services/ollama/override-values.yaml
      repoURL: https://helm.openwebui.com/
      targetRevision: 3.1.0
    - ref: values
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/ollama/istio/open-webui
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/ollama/istio/open-webui-pipelines
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/ollama/istio/ollama
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
