apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
    path: devqa/services/ollama/searxng
    targetRevision: HEAD
    kustomize:
      # commonLabels:
      #   app: searxng
      #   version: "1.0.0"
      #   env: devqa
      #   tier: services
      helmCharts:
      - name: searxng
        repo: https://charts.searxng.org
        version: "1.0.0"
        releaseName: searxng
        namespace: open-webui
        valuesFile: override-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
