apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: searxng
  namespace: open-webui
spec:
  hosts:
  # - searxng
  # - searxng.open-webui
  # - searxng.open-webui.svc.cluster.local
  - searxng.internal.magiccityit.com
  gateways:
  # - istio-ingress/internal-magiccityit-gateway
  - emissary/internal-magiccityit-gateway
  - mesh
  http:
  - route:
    - destination:
        host: searxng
        port:
          number: 8080