apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: clearml-serving-triton
  namespace: clearml
spec:
  host: clearml-serving-triton
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1