crds:
  enabled: false

## Provide a name to substitute for the full names of resources
##
fullnameOverride: "grafana"

grafana:
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true
    datasources:
      ## URL of prometheus datasource
      url: http://prometheus-prometheus.observability:9090/
      

defaultRules:
  create: false

global:
  rbac:
    create: false

alertmanager:
  enabled: false

## Flag to disable all the kubernetes component scrapers
##
kubernetesServiceMonitors:
  enabled: false

## Component scraping the kube api server
##
kubeApiServer:
  enabled: false

## Component scraping the kubelet and kubelet-hosted cAdvisor
##
kubelet:
  enabled: false

kubeControllerManager:
  enabled: false

## Component scraping coreDns. Use either this or kubeDns
##
coreDns:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: false

## Component scraping kube proxy
##
kubeProxy:
  enabled: false

## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: false

## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: false

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: false

## Deploy a Prometheus instance
##
prometheus:
  enabled: false

## Configuration for thanosRuler
## ref: https://thanos.io/tip/components/rule.md/
##
thanosRuler:

  ## Deploy thanosRuler
  ##
  enabled: false

