apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: internal-magiccityit-gateway
  # namespace: istio-ingress
  namespace: emissary
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    # istio: gateway # use istio default controller
    # app: istio-gateway
    app.kubernetes.io/name: emissary-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.internal.magiccityit.com"
    # - bookinfo.internal.magiccityit.com
    # - clearml-serving.internal.magiccityit.com
    # - searxng.internal.magiccityit.com
    # - open-webui.internal.magiccityit.com
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: internal-magiccityit-domain-tls
      httpsRedirect: true
    hosts:
    - "*.internal.magiccityit.com"
    # - bookinfo.internal.magiccityit.com
    # - clearml-serving.internal.magiccityit.com
    # - searxng.internal.magiccityit.com
    # - open-webui.internal.magiccityit.com