apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-tracing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jaeger-tracing
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: jaeger
      helm:
        valueFiles:
          - >-
            $values/devqa/services/jaeger-tracing/override-values.yaml
      repoURL: https://jaegertracing.github.io/helm-charts
      targetRevision: 3.4.0
    - ref: values
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/jaeger-tracing/gateway
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: getambassador.io
      kind: Mapping
      jsonPointers:
      - /spec/host