crds:
  enabled: false

## Provide a name to substitute for the full names of resources
##
# fullnameOverride: "stack"

grafana:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      # - job_name: 'istiod'
      #   kubernetes_sd_configs:
      #   - role: endpoints
      #     namespaces:
      #       names:
      #       - istio-system
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      #     action: keep
      #     regex: istiod;http-monitoring

      # - job_name: 'envoy-stats'
      #   metrics_path: /stats/prometheus
      #   kubernetes_sd_configs:
      #   - role: pod
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_pod_container_port_name]
      #     action: keep
      #     regex: '.*-envoy-prom'

      - job_name: minio-job
        bearer_token: <secret>
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
        - targets: ['localhost:9000']
