crds:
  enabled: false

## Provide a name to substitute for the full names of resources
##
fullnameOverride: "stack"

grafana:
  enabled: false
kube-state-metrics:
  selfMonitor:
    enabled: true
nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    darwin:
      enabled: false
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false


prometheus:
  prometheusSpec:
    ruleSelector:
      any: true
    serviceMonitorSelector:
      any: true
    podMonitorSelector:
      any: true
    probeSelector:
      any: true
    scrapeConfigSelector:
      any: true
