apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  hosts:
  - productpage
  - productpage.bookinfo
  - productpage.bookinfo.svc.cluster.local
  - bookinfo.internal.magiccityit.com
  gateways:
#   - istio-ingress/internal-magiccityit-gateway
  - emissary/internal-magiccityit-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080