istio_namespace: istio-system
deployment:
  # This only limits what Kiali will attempt to see, but Kiali Service Account has permissions to see everything.
  # For more control over what the Kial Service Account can see, use the Kiali Operator
  accessible_namespaces:
  - "**"
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
  logger:
    log_format: "text"
    log_level: "debug"
    time_field_format: "2006-01-02T15:04:05Z07:00"
    sampler_rate: "1"
auth:
  strategy: "anonymous"
external_services:
  custom_dashboards:
    enabled: true
    is_core: true
    namespace_label: "kubernetes_namespace"
    prometheus:
      auth:
        type: none
      url: http://prometheus-prometheus.observability:9090
  grafana:
    enabled: true
    # Grafana service name is "grafana" and is in the "telemetry" namespace.
    in_cluster_url: http://grafana.observability:3000
    # Public facing URL of Grafana
    url: https://grafana.internal.magiccityit.com

  tracing:
    # Enabled by default. Kiali will anyway fallback to disabled if
    # Jaeger is unreachable.
    enabled: true
    # Jaeger service name is "tracing" and is in the "telemetry" namespace.
    # Make sure the URL you provide corresponds to the non-GRPC enabled endpoint
    # if you set "use_grpc" to false.
    in_cluster_url: 'http://jaeger-tracing-query.jaeger-tracing:16685/jaeger'
    use_grpc: true
    is_core: true
    # Public facing URL of Jaeger
    url: 'https://jaeger.internal.magiccityit.com'

  prometheus:
    auth:
      type: none
    cache_duration: 10
    cache_enabled: true
    cache_expiration: 300
    health_check_url: ""
    is_core: true
    # Prometheus service name is "metrics" and is in the "telemetry" namespace
    url: http://prometheus-prometheus.observability:9090

  istio:
    component_status:
      components:
      - app_label: istiod
        is_core: true
        is_proxy: false
      - app_label: istio-gateway
        is_core: true
        is_proxy: true
      enabled: true
    config_map_name: istio
    envoy_admin_local_port: 15000
    istio_identity_domain: svc.cluster.local
    istio_injection_annotation: "sidecar.istio.io/inject"
    istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
    istiod_deployment_name: "istiod"
    root_namespace: istio-system

identity: {}

kiali_feature_flags:
  istio_injection_action: true
  # istio_upgrade_action: true
  certificates_information_indicators:
    enabled: true
    secrets:
    - cacerts
    - istio-ca-secret
  clustering:
    autodetect_secrets:
      enabled: true
      label: "kiali.io/multiCluster=true"
    clusters: []
  disabled_features: []
  validations:
    ignore: ["KIA1201"]

login_token:
  signing_key: ""

server:
  gzip_enabled: true
  port: 20001
  metrics_enabled: true
  metrics_port: 9090
  web_fqdn: kiali.internal.magiccityit.com