---
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentik
  namespace: emissary
spec:
  ambassador_id: [ "emissary" ]
  auth_service: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000
  tls: "true"
  proto: http
  timeout_ms: 5000
  include_body:
    max_bytes: 4096
    allow_partial: true
  status_on_error:
    code: 403
  failure_mode_allow: false

  # proto: grpc only, default is v2. If upgrading from 2.x then you must set this to v3.
  protocol_version: v3

  # proto: http only
  path_prefix: /outpost.goauthentik.io/auth/envoy
  allowed_request_headers:
  - cookie
  allowed_authorization_headers:
  - set-cookie
  - x-authentik-*
  - cookie
  add_linkerd_headers: false
