apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: open-webui
  namespace: open-webui
spec:
  hosts:
  # - open-webui
  # - open-webui.open-webui
  # - open-webui.open-webui.svc.cluster.local
  - open-webui.internal.magiccityit.com
  gateways:
  - istio-ingress/internal-magiccityit-gateway
  # - emissary/internal-magiccityit-gateway
  - mesh
  http:
  - route:
    - destination:
        host: open-webui
        port:
          number: 80