apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: open-webui
spec:
  hosts:
  - "open-webui.internal.magiccityit.com"
  gateways:
  - istio-ingress/internal-magiccityit-gateway
  http:
  - route:
    - destination:
        host: open-webui
        port:
          number: 80