apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
  namespace: emissary
spec:
  hostname: "*.internal.magiccityit.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: internal-magiccityit-domain-tls
    namespace: cert-manager