apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: minio
  namespace: minio
spec:
  hosts:
  - minio.internal.magiccityit.com
  - s3.internal.magiccityit.com
  gateways:
  - istio-ingress/internal-magiccityit-gateway
  - mesh
  http:
  - match:
    - authority:
        exact: minio.internal.magiccityit.com
    route:
    - destination:
        host: minio-console
        port:
          number: 9001
  - match:
    - authority:
        exact: s3.internal.magiccityit.com
    route:
    - destination:
        host: minio
        port:
          number: 9000