apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-ingress
  namespace: argocd
spec:
  destination:
    namespace: emissary
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - clusterrole-aggregation-controller
        - controller
  project: default
  sources:
    - chart: emissary-ingress
      helm:
        valueFiles:
          - >-
            $values/devqa/services/emissary-ingress/override-values.yaml
          - >-
            $values/devqa/services/emissary-ingress/istio-override-values.yaml
      repoURL: https://app.getambassador.io
      targetRevision: 8.9.1
    - ref: values
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/emissary-ingress/tracingservices
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/emissary-ingress/istio-integration
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
      directory:
        exclude: 'emissary-admin-port.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        cert-manager-tls: internal-magiccityit-domain
        istio-injection: enabled
