apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-magiccityit-domain-tls
  namespace: cert-manager
spec:
  secretName: internal-magiccityit-domain-tls
  issuerRef:
    name: letsencrypt-prod
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d before SSL will expire, renew it
  dnsNames:
    - "*.internal.magiccityit.com"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "cert-manager-tls=istio"
      kubed.appscode.com/sync: "cert-manager-tls=emissary"