apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      targetRevision: 1.32.2
      helm:
        valueFiles:
          - $values/devqa/services/tempo/override-values.yaml
      chart: tempo-distributed
    - repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      ref: values
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  # ignoreDifferences:
  #   - group: '*'
  #     kind: '*'
  #     managedFieldsManagers:
  #       - argocd-controller