# compatWithCPUManager: null
# migStrategy: null
# failOnInitError: true
# deviceListStrategy: envvar
# deviceIDStrategy: uuid
# nvidiaDriverRoot: /
# gdsEnabled: false
# mofedEnabled: false
# deviceDiscoveryStrategy: all

devicePlugin:
  enabled: true
gfd:
  enabled: true
nfd:
  nameOverride: node-feature-discovery
  enableNodeFeatureApi: true
runtimeClassName: nvidia
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        # On discrete-GPU based systems NFD adds the following label where 10de is the NVIDIA PCI vendor ID
        - key: feature.node.kubernetes.io/pci-10de.present
          operator: In
          values:
          - "true"
      - matchExpressions:
        # We allow a GPU deployment to be forced by setting the following label to "true"
        - key: "nvidia.com/gpu.present"
          operator: In
          values:
          - "true"