# compatWithCPUManager: null
# migStrategy: null
# failOnInitError: true
# deviceListStrategy: envvar
# deviceIDStrategy: uuid
# nvidiaDriverRoot: /
# gdsEnabled: false
# mofedEnabled: false
# deviceDiscoveryStrategy: all

gfd:
  enabled: true
# nfd:
#   nameOverride: node-feature-discovery
#   enableNodeFeatureApi: true
runtimeClassName: nvidia