defaults:
  # A-la-carte istio ingress gateway.
  # Must be installed in a separate namespace, to minimize access to secrets.
  gateways:
    istio-ingressgateway:
      serviceAnnotations:
        cloudprovider.harvesterhci.io/ipam: dhcp