apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: argocd.internal.magiccityit.com
  prefix: /
  service: argocd-server.argocd:443
  allow_upgrade:
  - websocket
  bypass_auth: true
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-cli
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  # NOTE: the port must be ignored if you have strip_matching_host_port enabled on envoy
  host: argocd.internal.magiccityit.com:443
  prefix: /
  service: argocd-server.argocd:80
  regex_headers:
    Content-Type: "^application/grpc.*$"
  grpc: true
  bypass_auth: true
