apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: bookinfo
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: bookinfo-v1.internal.magiccityit.com
  prefix: /productpage
  service: productpage.bookinfo:9080
  tls: istio-upstream