apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: clearml-agent
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: clearml-serving.internal.magiccityit.com
  prefix: /
  service: clearml-agent.clearml:10022
