apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: clearml-serving
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: clearml-serving-v1.internal.magiccityit.com
  prefix: /
  service: clearml-serving-inference.clearml:8080
  tls: istio-upstream