apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: diag
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: emissary-ingress.internal.magiccityit.com
  prefix: /ambassador/v0/diag/
  service: localhost:8877
  bypass_auth: true