apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grafana-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: grafana.internal.magiccityit.com
  prefix: /
  service: kube-prometheus-stack-grafana.monitoring