apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: ollama
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: open-webui.internal.magiccityit.com
  prefix: /
  service: open-webui.ollama:80
  allow_upgrade:
  - websocket
