apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: ollama
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: open-webui-v1.internal.magiccityit.com
  prefix: /
  service: open-webui.open-webui:80
  # tls: istio-upstream
