apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: open-webui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: open-webui-v1.internal.magiccityit.com
  prefix: /
  service: open-webui:80
  tls: istio-upstream
  timeout_ms: 30000
  allow_upgrade:
  - websocket
  bypass_auth: true