apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: prometheus-ui
  namespace: emissary
spec:
  ambassador_id: ["emissary"]
  host: prometheus.internal.magiccityit.com
  prefix: /
  service: kube-prom-stack-kube-prome-prometheus.observability:9090