# Explanation about each environment variables here:
# https://docs.searxng.org/admin/installation-docker.html#command-line
env:
  INSTANCE_NAME: "my-instance"
  BASE_URL: "https://searchxng.internal.magiccityit.com"
  AUTOCOMPLETE: "false"
  # MORTY_URL: "http://morty:8080"
  # MORTY_KEY: "mysecretkey"
  # BIND_ADDRESS: "0.0.0.0:8080"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
  