# Explanation about each environment variables here:
# https://docs.searxng.org/admin/installation-docker.html#command-line
env:
  INSTANCE_NAME: "my-instance"
  BASE_URL: "https://searchxng.internal.magiccityit.com"
  AUTOCOMPLETE: "false"
  # MORTY_URL: "http://morty:8080"
  # MORTY_KEY: "mysecretkey"
  # BIND_ADDRESS: "0.0.0.0:8080"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
  

searxng:
  config:
    use_default_settings: true
    server:
      secret_key: "f9e603d4191caab069b021fa0568391a33c8a837b470892c64461b5dd12464f4"
      limiter: false
      image_proxy: true
      port: 8080
      bind_address: "0.0.0.0"

    ui:
      static_use_hash: true

    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json
    # Uncomment when using the builtin rate limiter
    # See https://docs.searxng.org/src/searx.plugins.limiter.html#limiter-plugin
    # server.limiter: true
    # redis.url: redis://@searxng-redis:6379/0