apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: 'https://fluent.github.io/helm-charts'
      targetRevision: 0.28.0
      helm:
        valueFiles:
          - $values/prometheus-configuration-guide/services/fluentbit/microk8s-values.yaml
      chart: fluent-bit
    - repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      ref: values
      targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s