# -- Private image registry configuration
imageCredentials:
  # -- Use private authentication mode
  enabled: false

# -- ClearMl generic configurations
clearml:
  apiSecretName: clearml-serving
  apiAccessKey: "ClearML API Access Key"
  apiSecretKey: "ClearML API Secret Key"
  apiHost: https://app.clear.ml/
  filesHost: https://files.clear.ml
  webHost: https://app.clear.ml/
  defaultBaseServeUrl: http://127.0.0.1:8080/serve
  servingTaskId: "ClearML Serving Task ID"
  kafkaServeUrl: ""

# -- ClearML serving statistics configurations
clearml_serving_statistics:
  # -- Enable ClearML Serving Statistics
  enabled: true
  # -- Container Image
  image:
    repository: "allegroai/clearml-serving-statistics"
    tag: "1.3.0"
  # -- Node Selector configuration
  nodeSelector: {}
  # -- Tolerations configuration
  tolerations: []
  # -- Affinity configuration
  affinity: {}
  # -- Pod resources definition
  resources: {}
  extraEnvironment: []
  # -- Extra Python Packages to be installed in running pods
  extraPythonPackages: []
  #  - numpy==1.22.4
  #  - pandas==1.4.2
  # -- reference for files declared in existing ConfigMap will be mounted and read by pod (examples in values.yaml)
  existingAdditionalConfigsConfigMap: ""
  # -- reference for files declared in existing Secret will be mounted and read by pod (examples in values.yaml) if not overridden by existingAdditionalConfigsConfigMap
  existingAdditionalConfigsSecret: "clearml-serving"
  # -- files declared in this parameter will be mounted on internal folder /opt/clearml/config and read by pod (examples in values.yaml) if not overridden by existingAdditionalConfigsSecret
  additionalConfigs: {}
  #   additionalFile.conf: |
  #     <filecontent>

# -- ClearML serving inference configurations
clearml_serving_inference:
  # -- Container Image
  image:
    repository: "allegroai/clearml-serving-inference"
    tag: "1.3.0"
  # -- Node Selector configuration
  nodeSelector: {}
  # -- Tolerations configuration
  tolerations: []
  # -- Affinity configuration
  affinity: {}
  # -- Pod resources definition
  resources: {}
  # -- Extra environment variables
  extraEnvironment: []
  # -- Extra Python Packages to be installed in running pods
  extraPythonPackages: []
  #  - numpy==1.22.4
  #  - pandas==1.4.2
  # -- reference for files declared in existing ConfigMap will be mounted and read by pod (examples in values.yaml)
  existingAdditionalConfigsConfigMap: ""
  # -- reference for files declared in existing Secret will be mounted and read by pod (examples in values.yaml) if not overridden by existingAdditionalConfigsConfigMap
  existingAdditionalConfigsSecret: ""
  # -- files declared in this parameter will be mounted on internal folder /opt/clearml/config and read by pod (examples in values.yaml) if not overridden by existingAdditionalConfigsSecret
  additionalConfigs: {}
  #   additionalFile.conf: |
  #     <filecontent>
  # -- Autoscaling configuration
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 11
    targetCPU: 50
    targetMemory: 50

# -- ClearML serving Triton configurations
clearml_serving_triton:
  # -- Triton pod creation enable/disable
  enabled: false


# -- Configuration from https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  enabled: false

# -- Configuration from https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
prometheus:
  enabled: false

# -- Configuration from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  enabled: false