apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.2
  - path: devqa/services/istio/gateways
    repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        cert-manager-tls: istio