apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: istiod
      helm:
        valueFiles:
          - >-
            $values/devqa/services/istio/istiod/override-values.yaml
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
    - ref: values
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
    - path: devqa/services/istio/monitoring
      repoURL: https://github.com/jonathanelbailey/homelab.catalog.git
      targetRevision: HEAD
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - pilot-discovery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
